FROM node:alpine as build.stage
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:stable-alpine as production.stage
# 1. Copia i file statici nel path standard di Nginx
COPY --from=build.stage /app/dist /usr/share/nginx/html
# 2. Copia la configurazione specifica per il Router di Vue (History mode)
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]